# These are supported funding model platforms

github:niveshbirangal # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon:niveshbirangal # Replace with a single Patreon username
open_collective: niveshbirangal # Replace with a single Open Collective username
ko_fi:niveshbirangal # Replace with a single Ko-fi username
tidelift:niveshbirangal # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge:niveshbirangal # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay:niveshbirangal # Replace with a single Liberapay username
issuehunt:niveshbirangal # Replace with a single IssueHunt username
otechie:niveshbirangal # Replace with a single Otechie username
custom:https://niveshb.com # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
